#
# $Log: Makefile.Host,v $
# Revision 1.1  2006/01/09 22:05:21  shang
# first version
#
#
#

TOP = ../../..
include $(TOP)/config/CONFIG_APPS
include $(TOP)/src/physics/Makefile.OAG
include $(TOP)/config/RULES.Host

